### ISSUE TITLE
Create Design Document for a Well-Organized Database

### ISSUE THREAD

**Issue by aryker** [frc868/Scouting-System-2017#8]
Before starting on backend implementation, we should always put significant effort into database design. @karagenit, you gave an overview of a solid database design for this project. Could you add that to this project?

Ideally, designs should be mocked up graphically for ease of understanding. [MySQL Workbench](https://www.mysql.com/products/workbench/) has a nice tool to do this, and has a free version available for Windows, OS X, and Linux.

**Comment by karagenit** [comment]
I appreciate the use of the Assignees feature on Github :)

Since I doubt much work is going to be done on this repo anymore, I created a one for the [2018 Scouting System](https://github.com/frc868/2018-scouting). I put my Database Schema ideas in the README of that repository, which can be found [here](https://github.com/frc868/2018-scouting#database-schema).

If you want, I can copy what I wrote into this repo's README too.
